### PR TITLE
Update diffusers to support InstructPix2Pix pipeline

### PR DESCRIPTION
**Pull request by Hades32**
https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/pix2pix

### CODE REVIEW

**Comment by gadicc** [comment]
Thanks for the PR, @Hades32!

I've also had my eye on this one for a while `:)  So thanks for this.

I'll be merging a lot of stuff into `dev` later this week (everything from the `split` branch, to finally move forward with "v1"), and will rebase this into that straight afterwards.  I'll keep you posted!

Thanks again :)

**Comment by gadicc** [comment]
Ok I moved up my timetable a bit :sweat_smile: 
Merged everything to `dev` :muscle: 

The resulting merge conflict from your PR wasn't terrible but I wanted to update to the latest diffusers commit hash too, so unfortunately I won't get to merge this... sorry about that... but you really did succeed in nudging me to move things forward :raised_hands: 

Just note that everything I merged today bumps the `dev` branch from `v0` to `v1` (not officially released yet, but getting there).  There is a `dev-v0-final` branch pointing to the last `dev` commit of `v0` if relevant.  Otherwise see [Upgrading from v0 to v1](https://forums.kiri.art/t/wip-upgrading-from-v0-to-v1/116/2).

For latest diffusers (in my commit https://github.com/kiri-art/docker-diffusers-api/commit/87632aa2c32faddfeb049fe969884b568066edd3), you can either build from source in `dev` or simply use the docker image with `dev` [tag](https://hub.docker.com/repository/docker/gadicc/diffusers-api/tags?page=1&ordering=last_updated), i.e. `docker pull gadicc/diffusers-api:dev`.  On next merge to main, it will get tagged with appropriate semantic version too.

Hope that's all clear, not sure if you're ready to try out `v1` yet since it's not officially released... but I'm available for anything you need.  Thanks for  your continued support! :pray:

**Comment by Hades32** [comment]
Haha, it was just a single line, but very happy to help give some extra motivation :D 

Thanks - as always - for your great work! I'll let you know when I stumble over any issues

**Comment by gadicc** [comment]
🙏

**Pull request closed without merging**
