### PR TITLE
Stable Diffusion 2.0

### PR DESCRIPTION
**Pull request by Keep-up-sharma**
Some changes to support stable diffusion 2..0

### CODE REVIEW

**Comment by gadicc** [comment]
thanks, @Keep-up-sharma.  i rebased against `dev` and merged there.

**Comment by gadicc** [comment]
ps i'm not sure i really understood... i thought you were having issues with img2img?  we had SDv2 support about half an hour after the model was released. :sweat_smile:   On `dev` branch.

**Comment by Keep-up-sharma** [comment]
> ps i'm not sure i really understood... i thought you were having issues with img2img?  we had SDv2 support about half an hour after the model was released. :sweat_smile:   On `dev` branch.

I didn't know there were multiple branches 😅

**Comment by gadicc** [comment]
oh haha fair enough... i did try make this clear on all my discord posts but I've added a note about it too to the readme (on dev, will be merged to main soon as soon as banana's optimisation is working again so i can double check the image still optimises).  thanks!

**Pull request merged**
